import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {AppProps} from "next/app";
import {WebAppProvider} from "@/app/providers/WebAppProvider";
import {useRouter} from "next/router";

import "@/app/styles/globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function HomePage({Component, pageProps}: AppProps) {
    const router = useRouter();

    return (
        <WebAppProvider>
            <div className={`${inter.className} antialiased max-w-[420px]`}>
                <Component {...pageProps} />
            </div>
        </WebAppProvider>
    );
}

export default HomePage;
